[tool.poetry]
name = "easy-db"
version = "0.1.0"
description = ""
authors = ["core.ui <roman.thimian@me.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
sqlalchemy = "^2.0.25"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
